export const PartnerLogos = {
  StabilityAiLogo: "/partners/stability-ai-logo.png",
  MhayaLogo: "/partners/mhaya-logo.png",
  BearfiLogo: "/partners/bearfi-logo.jpg",
  TapGearLogo: "/partners/tapgear-logo.jpg",
  HybridLogo: "/partners/hybrid-logo.jpg",
  HabitLogo: "/partners/habit-logo.jpg",
  FrogsLogo: "/partners/frogs-logo.jpg",
  CogniXphereLogo: "/partners/cognixphere-logo.png",
  BombCryptoLogo: "/partners/bombcrypto-logo.png",
  CatPlanetsLogo: "/partners/catplanets-logo.png",
  Wagmi11Logo: "/partners/wagmi11-logo.jpg",
  TonFlashLogo: "/partners/tonflash-logo.jpg",
  NotMushLogo: "/partners/notmush-logo.jpg",
  WaViewAiLogo: "/partners/waviewai-logo.jpg",
  GalacticGoldLogo: "/partners/galacticgold-logo.jpg",
  DratonLogo: "/partners/draton-logo.jpg",
}